plugins {
    id 'com.android.application'
}

android {
    namespace 'id.biz.topron.official'
    compileSdk 36

    defaultConfig {
        applicationId 'id.biz.topron.official'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
